# paasta-mongodb-shard-vsphere 설정 파일 내용
---
name: paasta-mongodb-shard-service  # 서비스 배포이름(필수)
director_uuid: b63ac41b-8215-4926-bb43-5dcc982eff6a   #bosh status 에서 확인한 Director UUID을 입력(필수)

release:
  name: paasta-mongodb-shard  #서비스 릴리즈 이름(필수)
  version: 2.0   #서비스 릴리즈 버전(필수):latest 시 업로드된 서비스 릴리즈 최신버전

compilation:                           # 컴파일시 필요한 가상머신의 속성(필수)
  cloud_properties: # 컴파일 VM을 만드는 데 필요한 IaaS의 특정 속성 (instance_type, availability_zone)
    instance_type: monitoring          # 인스턴스 타입: Flavors 타입 (필수)
  network: default    # Networks block에서 선언한 network 이름(필수)
  reuse_compilation_vms: true     # 컴파일지 VM 재사용 여부(옵션)
  workers: 4              # 컴파일 하는 가상머신의 최대수(필수)

# this section describes how updates are handled
update:
  canaries: 1   # canary 인스턴스 수(필수)
  canary_watch_time: 30000  # canary 인스턴스가 수행하기 위한 대기 시간(필수)
  update_watch_time: 30000  # non-canary 인스턴스가 병렬로 update 하는 최대 개수(필수)
  max_in_flight: 4
networks:     # 네트워크 블록에 나열된 각 서브 블록이 참조 할 수있는 작업이 네트워크 구성을 지정, 네트워크 구성은 네트워크 담당자에게 문의 하여 작성 요망
- name: default
  subnets:
  - cloud_properties:
      net_id: b7c8c08f-2d3b-4a86-bd10-641cb6faa317
      security_groups: [bosh]
    dns:  # DNS 정보
    - 10.244.3.4
    - 8.8.8.8
    gateway: 10.244.3.1
    range: 10.244.3.0/24  # 사용할 네트워크 범위
    reserved:   # 설치시 제외할 IP 설정
    - 10.244.3.2 - 10.244.3.140
    static:
    - 10.244.3.141 - 10.244.3.170  #사용 가능한 IP 설정

resource_pools:               # 배포시 사용하는 resource pools를 명시하며 여러 개의 resource pools 을 사용할 경우 name 은 unique >해야함(필수)
- cloud_properties:
    instance_type: monitoring
  env:
    bosh: #password: dhvms09!
      password: $6$mwZOg/kA$r64mds4/xoqhW2tR8ck7oxmhqGiCBsDS5SWW/j8vgahvpdHkKJrb25/Wc2..CT3ja02qLgh0JB60RTP2ndjAh0
    #bosh:
    #  password: $6$4gDD3aV0rdqlrKC$2axHCxGKIObs6tAmMTqYCspcdvQXh3JJcvWOY2WGb4SrdXtnCyNaWlrf3WEqvYR2MYizEGp3kMmbpwBC6jsHt0
  name: small # 고유한 resource pool 이름
  network: default
  stemcell:
    name:  bosh-openstack-kvm-ubuntu-trusty-go_agent  # stemcell 이름(필수)
    version: 3309 # stemcell 버전(필수)


jobs:
  - name: mongodb_slave1  #작업 이름(필수): mongodb replica set의 slave 서버
    template: mongodb_slave   # job template 이름(필수)
    instances: 1  # job 인스턴스 수(필수)
    resource_pool: small   # resource_pools block에 정의한 resource pool 이름(필수)
    persistent_disk: 9000  # 영구적 디스크 사이즈 정의(옵션): 16G
    networks:   # 네트워크 구성정보
    - name: default   # Networks block에서 선언한 network 이름(필수)
      static_ips:   # 사용할 IP addresses 정의(필수)
      - 10.244.3.142
    properties:
      replSetName: op1 # replicaSet1 의 이름

  - name: mongodb_master1   #작업 이름(필수): mongodb replica set의 master 서버
    template: mongodb_master  # job template 이름(필수)
    instances: 1  # job 인스턴스 수(필수)
    resource_pool: small   # resource_pools block에 정의한 resource pool 이름(필수)
    persistent_disk: 9000  # 영구적 디스크 사이즈 정의(옵션): 16G
    networks:   # 네트워크 구성정보
    - name: default   # Networks block에서 선언한 network 이름(필수)
      static_ips:
      - 10.244.3.141   # 사용할 IP addresses 정의(필수)
    properties:
      replSet_hosts: ["10.244.3.141","10.244.3.142"] # 첫번째 Host는 replicaSet1의 master
      replSetName: op1 # replicaSet1 의 이름

  - name: mongodb_config
    template: mongodb_config
    instances: 1
    resource_pool: small
    persistent_disk: 9000  # 영구적 디스크 사이즈 정의(옵션): 16G
    networks:
    - name: default
      static_ips:
      - 10.244.3.150 

  - name: mongodb_shard
    template: mongodb_shard
    instances: 1
    resource_pool: small
    persistent_disk: 9000  # 영구적 디스크 사이즈 정의(옵션): 16G
    networks:
    - name: default
      static_ips:
      - 10.244.3.170
    properties:
      bindIp: 0.0.0.0
      configsvr_hosts: # mongodb_config hosts
      - 10.244.3.150

      repl_name_host_list: # mongodb_master properties
      - op1/10.244.3.141 # replicaSet1 의 이름/host
      # - op2/10.244.3.144 # replicaSet2 의 이름/host
      # - op3/10.244.3.147 # replicaSet3 의 이름/host

  - name: mongodb_broker  #작업 이름(필수): mongodb 서비스 브로커
    template: mongodb_broker  # job template 이름(필수)
    instances: 1  # job 인스턴스 수(필수)
    resource_pool: small   # resource_pools block에 정의한 resource pool 이름(필수)
    networks:   # 네트워크 구성정보
    - name: default   # Networks block에서 선언한 network 이름(필수)
      static_ips:   # 사용할 IP addresses 정의(필수)
      - 10.244.3.154

  - name : mongodb_broker_registrar   # 작업 이름: 서비스 브로커 등록
    template : mongodb_broker_registrar
    instances: 1
    lifecycle: errand   # bosh deploy시 vm에 생성되어 설치 되지 않고 bosh errand 로 실행할때 설정, 주로 테스트 용도에 쓰임
    resource_pool: small
    networks:
    - name: default
    properties:
      broker:   # 서비스 브로커 설정 정보
        host: 10.244.3.154   # 서비스 브로커 IP 
        name: Mongo-DB  # CF에서 서비스 브로커를 생성시 생기는 서비스 이름 브로커에 고정되어있는 값
        password: cloudfoundry  # 브로커 접근 아이디 비밀번호(필수)
        username: admin   # 브로커 접근 아이디(필수)
        protocol: http
        port: 8080  # 브로커 포트
      cf:
        admin_password: admin   # CF 사용자의 패스워드
        admin_username: admin   # CF 사용자 이름
        api_url: https://api.115.68.151.188.xip.io # CF 설치시 설정한 api uri 정보(필수)
    release: paasta-mongodb-shard

  - name : mongodb_broker_deregistrar   # 작업 이름: 서비스 브로커 삭제
    template : mongodb_broker_deregistrar
    instances: 1
    lifecycle: errand
    resource_pool: small
    networks:
    - name: default
    properties:
      broker:
        host: 10.244.3.154
        name: Mongo-DB
        password: cloudfoundry
        username: admin
        protocol: http
        port: 8080
      cf:
        admin_password: admin
        admin_username: admin
        api_url: https://api.115.68.151.188.xip.io
    release: paasta-mongodb-shard

meta:
  apps_domain: api.115.68.151.188.xip.io   # CF 설치시 설정한 apps 도메인 정보
  environment: null
  external_domain: api.115.68.151.188.xip.io   # CF 설치시 설정한 외부 도메인 정보
  nats:   # CF 설치시 설정한 nats 정보
    machines:
    - 10.244.3.11
    password: admin
    port: 4222
    user: nats
  syslog_aggregator: null

properties:
  mongodb:  # mongodb shard release의 여러 job에서 공통적으로 하용하는 properties
    # key는 shard를 구성할 때 mongos와 각 replicaSet의 인증을 하기위해 사용
    key: |
      +Qy+1icfeV8D2WXIfCojRjvYlryMVI2Ry+dAi8mYZ1H1Z9pDstRkOC0/oJYs0L/i
      +Dj/3PurWo8MJuqBYrWVGsRnsx31um0SVAgFZM2GQEKvHIByX5hq/MuHlulSLM0h
      GKkMT19zqDwFBFIN53jN0PLuuOnJ6FxZSb4cTLymfWM543WGpYx/31b8ehPYyeRp
      T7P2o2vUd9hecb8mQFxcjsBN7PTLwuPb5lK0BRL4Ze7rh6qeC8j7M3zimV8lX2X5
      9EtWlQP0ORYIlFpqijatZhS8Bf5AfI1EW6kZgfqwycl2ghxmSIbeleiqyQgYZNKQ
      yBXV9disuBXcKy4tsOjSFvKw7y61kjjQOn8KXElefokefdLbcrpeARP6LR9WwR1v
      ZTHcChfzWA4apHo6gJZkoqGVPjF4ArXTYxZfC+hHrsa5oe3XZjNapwV6XQfBNCuQ
      EihT3Td/B7iAUWJnGQvugFJwYKJ5EYOYubhk8QtO9QIvoZxQPDq9tgUsVgiQ6gty
      ZT83oxFAIgm3vky9l3uPwYi6jQ2FvsEJvDyiZl7gulOaC5UD/BdcM4Y5n/dxy/6Y
      qphWWuPsJwnYBXLJgwtTZ/NkYDYyX/tL9gyzXGPkpMMD7DofFjWEpJvHlVRKIxp1
      /zlxbVOMAmASgZDaqFperSQQyrfQqpuvAA8pRkWgorROyrsiRYYWlJZWWa4qHlI9
      OZ1dDp8o71l3v0SqsKbEtxINpdiUNx4OdafsMNN/KVxw9oGdrPXnDl5DomtmAoKZ
      uaCf3AQ3RsDeymgVX3j5EpLCHBhcPj+0B5tv4Yln652HAzDissOUKPyDf+PJaVRo
      OfDOkUvmuqnwl45DOoOtZ0BMw7hXGdgm6Xfv5jEmtSjJzQ1pfwHOOfiY+zZWhHAi
      ow/WNvLtUgNUhobi+OQb11bMMNNtmGWe+cZft6QzBsnd2xa/tAYTZDfAJ8OCvYQK
      e46UrHd54ZJFzdzicRZ8DeuU9G4K
    user: root  # admin 권한 사용자이름
    passwd: paasta  # admin 권한 사용자 비밀번호
#    replSetName: op
#    bindIp: 10.244.3.153 # shard server ip
    port: 27017   # mongodb port

  mongodb_broker:
    db_name: mongodb-broker # mongodb broker 관리용 데이터베이스
    authsource: admin   # mongodb broker 관리용 데이터베이스에 접근할 때 인증정보가 있는 데이터베이스
    hosts: 10.244.3.153  # mongodb Host
