# openpaas-mongodb-shard-aws 설정 파일 내용
---
name: paasta-mongodb-shard-service  # 서비스 배포이름(필수)

release:
  name: paasta-mongodb-shard  #서비스 릴리즈 이름(필수)
  version: "2.0"   #서비스 릴리즈 버전(필수):latest 시 업로드된 서비스 릴리즈 최신버전

stemcells:
- alias: default
  os: ((stemcell_os))
  version: "((stemcell_version))"

update:
  canaries: 1                                          # canary 인스턴스 수(필수)
  canary_watch_time: 30000-180000                      # canary 인스턴스가 수행하기 위한 대기 시간(필수)
  max_in_flight: 6                                     # non-canary 인스턴스가 병렬로 update 하는 최대 개수(필수)
  update_watch_time: 30000-180000                      # non-canary 인스턴스가 수행하기 위한 대기 시간(필수)

instance_groups:
- name: mongodb_slave1  #작업 이름(필수): mongodb replica set의 slave 서버
  azs:
  - z5
  instances: 2  # job 인스턴스 수(필수)
  vm_type: ((vm_type_small))              # cloud config 에 정의한 vm_type
  stemcell: default
  persistent_disk_type: 10GB              # cloud config 에 정의한 영구 디스크 타입 
  networks:
  - name: ((default_network_name))        # cloud config 에 정의한 network 이름
    static_ips:                           # 사용할 IP addresses
    - 10.30.107.202
    - 10.30.107.203
  properties:
    replSetName: op1 # replicaSet1 의 이름
  templates:
  - name: mongodb_slave                # job template 이름(필수)
    release: paasta-mongodb-shard

- name: mongodb_slave2  #작업 이름(필수): mongodb replica set의 slave 서버
  azs:
  - z5
  instances: 2  # job 인스턴스 수(필수)
  vm_type: ((vm_type_small))              # cloud config 에 정의한 vm_type
  stemcell: default
  persistent_disk_type: 10GB              # cloud config 에 정의한 영구 디스크 타입 
  networks:
  - name: ((default_network_name))        # cloud config 에 정의한 network 이름
    static_ips:                           # 사용할 IP addresses
    - 10.30.107.205
    - 10.30.107.206
  properties:
    replSetName: op2 # replicaSet1 의 이름
  templates:
  - name: mongodb_slave                # job template 이름(필수)
    release: paasta-mongodb-shard

- name: mongodb_slave3  #작업 이름(필수): mongodb replica set의 slave 서버
  azs:
  - z5
  instances: 2  # job 인스턴스 수(필수)
  vm_type: ((vm_type_small))              # cloud config 에 정의한 vm_type
  stemcell: default
  persistent_disk_type: 10GB              # cloud config 에 정의한 영구 디스크 타입 
  networks:
  - name: ((default_network_name))        # cloud config 에 정의한 network 이름
    static_ips:                           # 사용할 IP addresses
    - 10.30.107.208
    - 10.30.107.209
  properties:
    replSetName: op3 # replicaSet1 의 이름
  templates:
  - name: mongodb_slave                # job template 이름(필수)
    release: paasta-mongodb-shard

- name: mongodb_master1   #작업 이름(필수): mongodb replica set의 master 서버
  azs:
  - z5
  instances: 1  # job 인스턴스 수(필수)
  vm_type: ((vm_type_small))              # cloud config 에 정의한 vm_type
  stemcell: default
  persistent_disk_type: 10GB              # cloud config 에 정의한 영구 디스크 타입 
  networks:
  - name: ((default_network_name))        # cloud config 에 정의한 network 이름
    static_ips:                           # 사용할 IP addresses
    - 10.30.107.201
  properties:
    replSet_hosts: ["10.30.107.201","10.30.107.202","10.30.107.203"] # 첫번째 Host는 replicaSet1의 master
    replSetName: op1 # replicaSet1 의 이름
  templates:
  - name: mongodb_master                # job template 이름(필수)
    release: paasta-mongodb-shard

- name: mongodb_master2   #작업 이름(필수): mongodb replica set의 master 서버
  azs:
  - z5
  instances: 1  # job 인스턴스 수(필수)
  vm_type: ((vm_type_small))              # cloud config 에 정의한 vm_type
  stemcell: default
  persistent_disk_type: 10GB              # cloud config 에 정의한 영구 디스크 타입 
  networks:
  - name: ((default_network_name))        # cloud config 에 정의한 network 이름
    static_ips:                           # 사용할 IP addresses
    - 10.30.107.204
  properties:
    replSet_hosts: ["10.30.107.204","10.30.107.205","10.30.107.206"] # 첫번째 Host는 replicaSet1의 master
    replSetName: op2 # replicaSet1 의 이름
  templates:
  - name: mongodb_master                # job template 이름(필수)
    release: paasta-mongodb-shard

- name: mongodb_master3   #작업 이름(필수): mongodb replica set의 master 서버
  azs:
  - z5
  instances: 1  # job 인스턴스 수(필수)
  vm_type: ((vm_type_small))              # cloud config 에 정의한 vm_type
  stemcell: default
  persistent_disk_type: 10GB              # cloud config 에 정의한 영구 디스크 타입 
  networks:
  - name: ((default_network_name))        # cloud config 에 정의한 network 이름
    static_ips:                           # 사용할 IP addresses
    - 10.30.107.207
  properties:
    replSet_hosts: ["10.30.107.207","10.30.107.208","10.30.107.209"] # 첫번째 Host는 replicaSet1의 master
    replSetName: op3 # replicaSet1 의 이름
  templates:
  - name: mongodb_master                # job template 이름(필수)
    release: paasta-mongodb-shard

- name: mongodb_config   #작업 이름(필수): mongodb  mongodb_config
  azs:
  - z5
  instances: 3  # job 인스턴스 수(필수)
  vm_type: ((vm_type_small))              # cloud config 에 정의한 vm_type
  stemcell: default
  persistent_disk_type: 10GB              # cloud config 에 정의한 영구 디스크 타입 
  networks:
  - name: ((default_network_name))        # cloud config 에 정의한 network 이름
    static_ips:                           # 사용할 IP addresses
    - 10.30.107.210
    - 10.30.107.211
    - 10.30.107.212
  templates:
  - name: mongodb_config                # job template 이름(필수)
    release: paasta-mongodb-shard

- name: mongodb_shard   #작업 이름(필수): mongodb mongodb_shard
  azs:
  - z5
  instances: 1  # job 인스턴스 수(필수)
  vm_type: ((vm_type_small))              # cloud config 에 정의한 vm_type
  stemcell: default
  networks:
  - name: ((default_network_name))        # cloud config 에 정의한 network 이름
    static_ips:                           # 사용할 IP addresses
    - 10.30.107.213
  properties:
    bindIp: 0.0.0.0
    configsvr_hosts: # mongodb_config hosts
    - 10.30.107.210
    - 10.30.107.211
    - 10.30.107.212
    repl_name_host_list: # mongodb_master properties
    - op1/10.30.107.201 # replicaSet1 의 이름/host
    - op2/10.30.107.204 # replicaSet2 의 이름/host
    - op3/10.30.107.207 # replicaSet3 의 이름/host
  templates:
  - name: mongodb_shard                # job template 이름(필수)
    release: paasta-mongodb-shard

- name: mongodb_broker  #작업 이름(필수): mongodb 서비스 브로커
  azs:
  - z5
  instances: 1  # job 인스턴스 수(필수)
  vm_type: ((vm_type_small))              # cloud config 에 정의한 vm_type
  stemcell: default
  networks:
  - name: ((default_network_name))        # cloud config 에 정의한 network 이름
    static_ips:                           # 사용할 IP addresses
    - 10.30.107.214
  templates:
  - name: mongodb_broker                # job template 이름(필수)
    release: paasta-mongodb-shard

- name: mongodb_broker_registrar   # 작업 이름: 서비스 브로커 등록
  azs:
  - z5
  instances: 1  # job 인스턴스 수(필수)
  lifecycle: errand   # bosh deploy시 vm에 생성되어 설치 되지 않고 bosh errand 로 실행할때 설정, 주로 테스트 용도에 쓰임
  vm_type: ((vm_type_small))              # cloud config 에 정의한 vm_type
  stemcell: default
  networks:
  - name: ((default_network_name))        # cloud config 에 정의한 network 이름
  properties:
    broker:   # 서비스 브로커 설정 정보
      host: 10.30.107.214   # 서비스 브로커 IP 
      name: Mongo-DB  # CF에서 서비스 브로커를 생성시 생기는 서비스 이름 브로커에 고정되어있는 값
      password: cloudfoundry  # 브로커 접근 아이디 비밀번호(필수)
      username: admin   # 브로커 접근 아이디(필수)
      protocol: http
      port: 8080  # 브로커 포트
    cf:
      admin_password: admin   # CF 사용자의 패스워드
      admin_username: admin_test   # CF 사용자 이름
      api_url: https://api.115.68.46.189.xip.io  # CF 설치시 설정한 api uri 정보(필수)
  templates:
  - name: mongodb_broker_registrar                # job template 이름(필수)
    release: paasta-mongodb-shard

- name: mongodb_broker_deregistrar   # 작업 이름: 서비스 브로커 등록
  azs:
  - z5
  instances: 1  # job 인스턴스 수(필수)
  lifecycle: errand   # bosh deploy시 vm에 생성되어 설치 되지 않고 bosh errand 로 실행할때 설정, 주로 >테스트 용도에 쓰임
  vm_type: ((vm_type_small))              # cloud config 에 정의한 vm_type
  stemcell: default
  networks:
  - name: ((default_network_name))        # cloud config 에 정의한 network 이름
  properties:
    broker:   # 서비스 브로커 설정 정보
      host: 10.30.107.214   # 서비스 브로커 IP 
      name: Mongo-DB  # CF에서 서비스 브로커를 생성시 생기는 서비스 이름 브로커에 고정되어있는 값
      password: cloudfoundry  # 브로커 접근 아이디 비밀번호(필수)
      username: admin   # 브로커 접근 아이디(필수)
      protocol: http
      port: 8080  # 브로커 포트
    cf:
      admin_password: admin   # CF 사용자의 패스워드
      admin_username: admin_test   # CF 사용자 이름
      api_url: https://api.115.68.46.189.xip.io  # CF 설치시 설정한 api uri 정보(필수)
  templates:
  - name: mongodb_broker_deregistrar                # job template 이름(필수)
    release: paasta-mongodb-shard

properties:
  mongodb:  # mongodb shard release의 여러 job에서 공통적으로 하용하는 properties
    # key는 shard를 구성할 때 mongos와 각 replicaSet의 인증을 하기위해 사용
    key: |
      +Qy+1icfeV8D2WXIfCojRjvYlryMVI2Ry+dAi8mYZ1H1Z9pDstRkOC0/oJYs0L/i
      +Dj/3PurWo8MJuqBYrWVGsRnsx31um0SVAgFZM2GQEKvHIByX5hq/MuHlulSLM0h
      GKkMT19zqDwFBFIN53jN0PLuuOnJ6FxZSb4cTLymfWM543WGpYx/31b8ehPYyeRp
      T7P2o2vUd9hecb8mQFxcjsBN7PTLwuPb5lK0BRL4Ze7rh6qeC8j7M3zimV8lX2X5
      9EtWlQP0ORYIlFpqijatZhS8Bf5AfI1EW6kZgfqwycl2ghxmSIbeleiqyQgYZNKQ
      yBXV9disuBXcKy4tsOjSFvKw7y61kjjQOn8KXElefokefdLbcrpeARP6LR9WwR1v
      ZTHcChfzWA4apHo6gJZkoqGVPjF4ArXTYxZfC+hHrsa5oe3XZjNapwV6XQfBNCuQ
      EihT3Td/B7iAUWJnGQvugFJwYKJ5EYOYubhk8QtO9QIvoZxQPDq9tgUsVgiQ6gty
      ZT83oxFAIgm3vky9l3uPwYi6jQ2FvsEJvDyiZl7gulOaC5UD/BdcM4Y5n/dxy/6Y
      qphWWuPsJwnYBXLJgwtTZ/NkYDYyX/tL9gyzXGPkpMMD7DofFjWEpJvHlVRKIxp1
      /zlxbVOMAmASgZDaqFperSQQyrfQqpuvAA8pRkWgorROyrsiRYYWlJZWWa4qHlI9
      OZ1dDp8o71l3v0SqsKbEtxINpdiUNx4OdafsMNN/KVxw9oGdrPXnDl5DomtmAoKZ
      uaCf3AQ3RsDeymgVX3j5EpLCHBhcPj+0B5tv4Yln652HAzDissOUKPyDf+PJaVRo
      OfDOkUvmuqnwl45DOoOtZ0BMw7hXGdgm6Xfv5jEmtSjJzQ1pfwHOOfiY+zZWhHAi
      ow/WNvLtUgNUhobi+OQb11bMMNNtmGWe+cZft6QzBsnd2xa/tAYTZDfAJ8OCvYQK
      e46UrHd54ZJFzdzicRZ8DeuU9G4K
    user: root  # admin 권한 사용자이름
    passwd: openpaas  # admin 권한 사용자 비밀번호
    port: 27017   # mongodb port

  mongodb_broker:
    db_name: mongodb-broker # mongodb broker 관리용 데이터베이스
    authsource: admin   # mongodb broker 관리용 데이터베이스에 접근할 때 인증정보가 있는 데이터베이스
    hosts: 10.30.107.213 # mongodb Host
